### ISSUE TITLE
Ccc

### ISSUE THREAD

**Issue by huntercfreeman** [huntercfreeman/Walk#89]
2025-06-19:

![Image](https://github.com/user-attachments/assets/94e2e572-b226-48cc-8cdb-e71e141e2643)

---

**Comment by huntercfreeman** [comment]
[TextEditorViewModelPersistentState.cs#L75](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/TextEditor/TextEditors/Models/Internals/TextEditorViewModelPersistentState.cs#L75)

![Image](https://github.com/user-attachments/assets/2b1736f7-c3ec-4f25-aa85-448506168e96)

---

[CSharpCompilerService.cs#L786](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/CompilerServices/CSharp/CompilerServiceCase/CSharpCompilerService.cs#L786)

![Image](https://github.com/user-attachments/assets/e073be09-8e1c-402a-bb96-ec43ddcc2a6f)

**Comment by huntercfreeman** [comment]
Shift + Tab when space tab width is tab key behavior sometimes deletes a the first character on a line?

**Comment by huntercfreeman** [comment]
Go ahead and ignore me.

I will never harm anyone.

I will just sit here making an IDE, while at the surface level appearing as a bad person with the things I say.

If you think too hard about my motives for making the IDE, you'll start to feel bad for me.

So it's better that you take these things at face value.

Because one day I will die, and this repo will fade into obscurity. It is better this way.

**Comment by huntercfreeman** [comment]
Ternary statements

![Image](https://github.com/user-attachments/assets/ec53d3ed-1df4-46d1-a339-6864d706c5e7)

**Comment by huntercfreeman** [comment]
[WalkCommonInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Installations/Displays/WalkCommonInitializer.razor)

```razor
<Walk.Common.RazorLib.Drags.Displays.DragInitializer/>
<Walk.Common.RazorLib.Dialogs.Displays.DialogInitializer/>
<Walk.Common.RazorLib.Widgets.Displays.WidgetInitializer/>
<Walk.Common.RazorLib.Notifications.Displays.NotificationInitializer/>
<Walk.Common.RazorLib.Dropdowns.Displays.DropdownInitializer/>
<Walk.Common.RazorLib.Outlines.Displays.OutlineInitializer/>
<Walk.Common.RazorLib.Tooltips.Displays.TooltipInitializer/>
```

[DragInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Drags/Displays/DragInitializer.razor)
[DialogInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Dialogs/Displays/DialogInitializer.razor)
[WidgetInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Widgets/Displays/WidgetInitializer.razor)
[NotificationInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Notifications/Displays/NotificationInitializer.razor)
[DropdownInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Dropdowns/Displays/DropdownInitializer.razor)
[OutlineInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Outlines/Displays/OutlineInitializer.razor)
[TooltipInitializer.razor](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/Tooltips/Displays/TooltipInitializer.razor)

---

I want to investigate consolidating these into a single component.

**Comment by huntercfreeman** [comment]
[TextEditorViewModelSlimDisplay.razor.cs#L260 | OnAfterRenderAsync(...)](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/TextEditor/TextEditors/Displays/TextEditorViewModelSlimDisplay.razor.cs#L260):

You can only tell whether to invoke `base.SomeOverridenMethod()` by reading documentation / reading source code. And furthermore you can only tell whether to run your code first, after, or etc... by doing the previously stated thing?

`await base.OnAfterRenderAsync(firstRender);` does nothing beyond creating async overhead / method invocation overhead / copying of the bool overhead and ...?

```csharp
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    // .... my code

    await base.OnAfterRenderAsync(firstRender);
}
```

```csharp
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    await base.OnAfterRenderAsync(firstRender);

    // .... my code
}
```

```csharp
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    // .... my code
}
```

**Comment by huntercfreeman** [comment]
![Image](https://github.com/user-attachments/assets/c13c30ee-7c3a-4159-941d-b94efd447fb5)

**Comment by huntercfreeman** [comment]
[walkCommon.css](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Common/wwwroot/walkCommon.css) -- okay

[walkTextEditor.css](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/TextEditor/wwwroot/walkTextEditor.css) -- okay

[walkIde.css](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Ide/Ide.RazorLib/wwwroot/walkIde.css):
- [walkIde.css#L180](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Ide/Ide.RazorLib/wwwroot/walkIde.css#L180):
```css
/* not a big deal */
.di_ide_input-file-display-bottom-controls-non-text .di_button:not(:first-of-type) {
    margin-left: var(--di_ide_input-file-display-bottom-controls-non-text-buttons-margin-left);
}
```
- [walkIde.css#L295](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Ide/Ide.RazorLib/wwwroot/walkIde.css#L295):
```css
/* wtf is this? / it starts on di_te_text-editor so I really would like to remove it. */
.di_te_text-editor-input-cursor-size .di_te_text-editor {
    min-height: initial;
}
```
- [walkIde.css#L349](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Ide/Ide.RazorLib/wwwroot/walkIde.css#L349)
```css
/* Red flag that it starts on a span and then goes into descendent selection */
.di_ide_panel_left .di_ide_panel-tabs .di_ide_panel-tab span {
    writing-mode: vertical-rl;
    text-orientation: mixed;
    -webkit-transform: rotate(180deg);
    -moz-transform: rotate(180deg);
    -ms-transform: rotate(180deg);
    -o-transform: rotate(180deg);
    transform: rotate(180deg);
}
```
- [walkIde.css#L363](https://github.com/huntercfreeman/Walk/blob/main/Source/Lib/Ide/Ide.RazorLib/wwwroot/walkIde.css#L363)
```css
/* Red flag that it starts on a span and then goes into descendent selection */
.di_ide_panel_right .di_ide_panel-tabs .di_ide_panel-tab span {
    writing-mode: vertical-rl;
    text-orientation: mixed;
}
```
